from centos:centos7
run yum -y install git
run yum -y install nodejs
run npm install -g yarn
run git clone https://github.com/vuejs/vuejs.org.git
COPY . /vuejs.org
WORKDIR /vuejs.org
run yarn && yarn build